export const gender = ['Male', 'Female'];
export const emergencyType = ['Accident', 'Cardiac', 'trauma'];
export const priorityLevel = ['1 - Highest','2 - High','3 - Medium','4 - Low','5 - Least']
export const caseStatus = ["Assigned", "On the Way", "On Scene", "At Hospital", "Closed"];
export const bloodGroup = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];
export const ambulanceType = ['Basic', 'ICU', 'Neonatal'];
export const ambulanceStatus = ['Available', 'Not available'];
export const shiftType = ['regular', 'emergency_override'];
export const roles = ['Admin', 'Emergency response staff', 'Triage staff', 'Patient']
export const staffRoles = ['Admin', 'Emergency response staff', 'Triage staff']